### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by TIGER96** [Telematica/YouTubeTelegramChannel#1]
Hello. Please write readme for installing the bot. What system should be and how to make autorun. Thanks.

**Comment by Telematica** [comment]
@TIGER96 I’ll migrate this repo to TypeScript and make some improvements, stay tune!

**Comment by Telematica** [comment]
@TIGER96 A brand new version of the scrapper it's out. Check it out.

**Comment by Telematica** [comment]
Check `readme.md `file.
